version: '3.8'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db_campanhas'
      MYSQL_USER: 'user_campanhas'
      MYSQL_PASSWORD: 'user_campanhas_pass'
      MYSQL_ROOT_PASSWORD: 'user_campanhas_root_pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
